# Generated by Django 3.2.4 on 2021-06-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mandeep_Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default="Mandeep's Blog", max_length=255),
        ),
    ]
