# Generated by Django 3.2.4 on 2021-06-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mandeep_Blog', '0003_auto_20210608_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Uncategorised', max_length=255),
        ),
    ]
